aws_region              = "us-east-1"
vpc_cidr                = "10.1.0.0/16"
azs                     = ["us-east-1a", "us-east-1b", "us-east-1c"]
eks_cluster_version     = "1.25"
eks_node_instance_types = ["t3.micro"]
db_instance_class       = "db.t3.micro"
db_name                 = "opswatdb"
db_username             = "produser"
db_password             = "prodpass"
rabbitmq_user           = "rmqprod"
rabbitmq_pass           = "rmqprodpass"